@startuml  Sequence Diagram
title  Sequence Diagram



@enduml

@startuml Set Alarm Time Sequence Diagram
title Set Alarm Time Sequence Diagram

participant user

participant alarm_clock

participant timer



The user sets the time on system

The alarm clock stores the time in the timer

@enduml