on:
  workflow_call:

jobs:

  build_python_artifacts:
    name: Build Artifacts
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./python
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9.18
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.18

      - name: Install the AaC Package
        run: pip install aac-puml -e .

      - name: List Transitive Dependencies
        run: pipdeptree

      - name: Build distribution package
        run: python -m build

      - name: Upload Python Wheel
        uses: actions/upload-artifact@v4
        with:
          name: aac_puml
          path: python/dist/aac_puml
          if-no-files-found: error
          overwrite: true

      - name: Build Documentation
        run: |
          cp -R ../docs/ ./docs
          cd ./docs
          sphinx-build source doc_artifacts

      - name: Upload Documentation
        uses: actions/upload-artifact@v4
        with:
          name: aac-puml-docs
          path: python/docs/doc_artifacts
          overwrite: true
